import { ObjectId } from "mongodb";

export interface House {
  _id: ObjectId;
  listing_url: string;
  name: string;
  summary: string;
  space: string;
  description: string;
  neighborhood_overview: string;
  notes: string;
  transit: string;
  access: string;
  interaction: string;
  house_rules: string;
  property_type: string;
  room_type: string;
  bed_type: string;
  minimum_nights: string;
  maximum_nights: string;
  cancellation_policy: string;
  last_scraped: Object;
  calendar_last_scraped: Object;
  first_review?: Object;
  last_review?: Object;
  accommodates: Number;
  bedrooms: Number;
  beds: Number;
  number_of_reviews: Number;
  bathrooms: Object;
  amenities: Array<string>;
  price: Object;
  weekly_price?: Object;
  monthly_price?: Object;
  security_deposit?: Object;
  cleaning_fee?: Object;
  extra_people: Object;
  guests_included: Object;
  images: Object;
  host: Object;
  address: Object;
  availability: Object;
  review_scores: Object;
  reviews: Array<Object>;
}
